### PR TITLE
Making --contract optional when using point-deploy from deployspace

### PR DESCRIPTION
**Pull request by diogosmendonca**

### CODE REVIEW

**Comment by tankakatan** [comment]
Thanks @diogosmendonca, could you please retarget all your PR to `develop` instead.

**Comment by jensendarren** [comment]
@diogosmendonca for this story we need to modify `deploy-from-deployspace.sh` file, not `deploy-sites.sh`. I'll revert this change and discuss with you.

**Review by jensendarren — CHANGES_REQUESTED** [review]
The `point-deploy` script is no longer able to deploy the Smart Contracts when I tested this. I've updated the story with a 'definition of done' as follows (more details are on the story card): 

**Definition of Done**

* If executed like so: `point-deploy --contracts` then the contracts are deployed
* If executed like so `point-deploy` then the contracts are not deployed.

**Comment by diogosmendonca** [comment]
I added the --contracts param to the point-deploy script. Now should works.

**Review by jensendarren — APPROVED** [review]

**Pull request merged**
